# Generated by Django 3.1.3 on 2020-12-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201204_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transpipeuser',
            options={'permissions': (('can_transcript_all_languages', 'Can transcript ALL languages'), ('can_translate_all_languages', 'Can translate ALL languages'), ('can_see_all_courses', 'Can see ALL courses'), ('download_summary', 'Can download summary'))},
        ),
    ]
