# Generated by Django 3.1.4 on 2021-01-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0003_auto_20201126_0341'),
        ('core', '0004_auto_20201204_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='transpipeuser',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, to='subtitles.Course'),
        ),
        migrations.AlterField(
            model_name='transpipeuser',
            name='assigned_languages',
            field=models.ManyToManyField(blank=True, to='subtitles.IsoLanguage'),
        ),
    ]
