# Generated by Django 3.1.4 on 2021-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210105_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='transpipeuser',
            name='tenants',
            field=models.ManyToManyField(related_name='tenants_list', to='core.Tenant'),
        ),
    ]
