# Generated by Django 3.1.4 on 2021-07-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transpipeuser_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='all_courses_visible',
            field=models.BooleanField(default=True),
        ),
    ]
