# Generated by Django 3.1.4 on 2021-09-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_all_courses_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='transpipeuser',
            name='initials',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
