# Generated by Django 3.1.4 on 2021-09-03 00:22

from django.db import migrations


def calculate_initials(apps, schema_editor):
    TranspipeUser = apps.get_model("core", "TranspipeUser")

    def get_initials(user):
        initials = ""
        if user.first_name:
            initials += user.first_name[0].upper()

        if user.last_name:
            initials += user.last_name[0].upper()

        if len(initials) < 2:
            initials += user.username[0].upper()

        return initials

    user: TranspipeUser
    for user in TranspipeUser.objects.all():
        user.initials = get_initials(user)
        user.save(update_fields=['initials'])


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_transpipeuser_initials'),
    ]

    operations = [
        migrations.RunPython(calculate_initials)
    ]
