# Generated by Django 3.1.4 on 2021-09-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210903_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transpipeuser',
            name='initials',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
