# Generated by Django 3.1.3 on 2020-11-20 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('ext_id', models.CharField(max_length=200, unique=True)),
                ('teacher', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ext_id', models.CharField(max_length=200, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.course')),
            ],
        ),
        migrations.CreateModel(
            name='IsoLanguage',
            fields=[
                ('iso_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('is_rtl', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN', 'In Progress'), ('AU', 'Auto Generated'), ('RE', 'Reviewed'), ('UP', 'Uploaded by user'), ('PU', 'Published')], default='IN', max_length=2)),
                ('origin', models.CharField(choices=[('MLLP', 'MLLP'), ('AWS', 'AWS'), ('MANU', 'Manual upload'), ('MOOC', 'Downloaded from MOOC platform')], default='MANU', max_length=4)),
                ('is_transcript', models.BooleanField()),
                ('last_update', models.DateTimeField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.isolanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('ext_id', models.CharField(max_length=200, unique=True)),
                ('summary', models.TextField(null=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.coursesection')),
                ('original_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.isolanguage')),
            ],
        ),
        migrations.CreateModel(
            name='SubtitleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('file', models.FileField(max_length=500, null=True, upload_to='subtitles/')),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.subtitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.video'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.isolanguage'),
        ),
        migrations.CreateModel(
            name='AWSupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=200)),
                ('stage_id', models.CharField(max_length=200, null=True)),
                ('upload_date', models.DateTimeField(null=True)),
                ('source_lang', models.CharField(default='de', max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.video')),
            ],
        ),
    ]
