# Generated by Django 3.1.3 on 2020-11-26 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201123_1420'),
        ('subtitles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsupload',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursesection',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitle',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtitlefile',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
            preserve_default=False,
        ),
    ]
