# Generated by Django 3.1.4 on 2021-01-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0003_auto_20201126_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='translated_languages',
            field=models.ManyToManyField(related_name='translated', to='subtitles.IsoLanguage'),
        ),
    ]
