# Generated by Django 3.1.4 on 2021-02-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0007_video_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sync_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('INITIAL', 'Initial')], default='INITIAL', max_length=200),
        ),
    ]
