# Generated by Django 3.1.4 on 2021-02-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0008_course_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='index',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='index',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='status',
            field=models.CharField(choices=[('IT', 'Initial'), ('IN', 'In Progress'), ('AU', 'Auto Generated'), ('RE', 'Reviewed'), ('UP', 'Uploaded by user'), ('PU', 'Published'), ('QU', 'Queued'), ('WA', 'Waiting for review'), ('CH', 'Changes Requested')], default='IN', max_length=2),
        ),
    ]
