# Generated by Django 3.1.4 on 2021-02-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0010_auto_20210223_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='translated_languages',
        ),
        migrations.AddField(
            model_name='course',
            name='translated_languages',
            field=models.ManyToManyField(related_name='translated', to='subtitles.AssignedLanguage'),
        ),
    ]
