# Generated by Django 3.1.4 on 2021-02-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0011_auto_20210223_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='translated_languages',
        ),
        migrations.AddField(
            model_name='course',
            name='transcription_service',
            field=models.CharField(choices=[('MLLP', 'MLLP'), ('AWS', 'AWS'), ('MANUAL', 'Manual')], default='MANUAL', max_length=255),
        ),
    ]
