# Generated by Django 3.1.4 on 2021-03-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0012_auto_20210223_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='item_id',
            field=models.CharField(db_index=True, max_length=512, null=True, unique=True),
        ),
    ]
