# Generated by Django 3.1.4 on 2021-03-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0013_video_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['index'], 'permissions': (('start_translation', 'Can start translation'), ('start_transcription', 'Can start transcription'))},
        ),
    ]
