# Generated by Django 3.1.4 on 2021-04-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210105_0143'),
        ('subtitles', '0014_auto_20210305_1402'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('tenant_id', 'ext_id')},
        ),
    ]
