# Generated by Django 3.1.4 on 2021-04-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210105_0143'),
        ('subtitles', '0015_auto_20210407_0149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('tenant_id', 'ext_id')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('tenant_id', 'ext_id')},
        ),
    ]
