# Generated by Django 3.1.4 on 2021-04-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0017_auto_20210407_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsupload',
            name='aws_config',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='awsupload',
            name='target_langs',
            field=models.ManyToManyField(to='subtitles.IsoLanguage'),
        ),
        migrations.AddField(
            model_name='video',
            name='workflow_status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
