# Generated by Django 3.1.4 on 2021-04-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0019_subtitle_is_automatic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'permissions': (('upload_subtitle_file', 'Can upload subtitle file'), ('fetch_subtitle', 'Can fetch subtitle'), ('publish_subtitle_to_xikolo', 'Can publish subtitle to xikolo'), ('approve_subtitle', 'Can spprove subtitle'), ('request_changes_subtitle', 'Request changes'), ('start_workflow_subtitle', 'Start workflow'))},
        ),
    ]
