# Generated by Django 3.1.4 on 2021-07-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0023_auto_20210618_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='workflow_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
