# Generated by Django 3.1.4 on 2021-07-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0024_video_workflow_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['index'], 'permissions': (('start_translation', 'Can start translation'), ('start_transcription', 'Can start transcription'), ('start_standalone_translation', 'Can start standalone translation'))},
        ),
    ]
