# Generated by Django 3.1.4 on 2021-09-02 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subtitles', '0025_auto_20210726_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='assigned_user',
            field=models.ManyToManyField(related_name='assigned_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
