# Generated by Django 3.1.4 on 2021-09-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0026_subtitle_assigned_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['index'], 'permissions': (('start_translation', 'Can start translation'), ('start_transcription', 'Can start transcription'), ('start_standalone_translation', 'Can start standalone translation'), ('assign_user', 'Can assign user to subtitles'))},
        ),
        migrations.AlterField(
            model_name='course',
            name='sync_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('INITIAL', 'Initial'), ('SKELETON', 'Skeleton')], default='INITIAL', max_length=200),
        ),
    ]
