# Generated by Django 3.1.4 on 2021-09-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subtitles', '0029_subtitleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitleassignment',
            name='subtitle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.subtitle'),
        ),
        migrations.AlterField(
            model_name='subtitleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
