# Generated by Django 3.1.4 on 2021-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0030_auto_20210924_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='assigned_user',
        ),
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='video',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
