# Generated by Django 3.1.4 on 2021-10-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0031_auto_20210929_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
