# Generated by Django 3.2.8 on 2021-10-26 22:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0032_auto_20211004_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url_lecturer',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url_slides',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
