# Generated by Django 3.2.8 on 2021-10-27 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0033_auto_20211027_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video_url_pip',
        ),
    ]
