# Generated by Django 3.2.8 on 2021-12-17 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20210907_0230'),
        ('subtitles', '0034_rename_video_url_video_video_url_pip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.CharField(choices=[('MLLP', 'MLLP'), ('AWS_TRANSCRIPTION', 'AWS Transcription'), ('AWS_TRANSLATION', 'AWS Translation'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=128)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subtitle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subtitles.subtitle')),
                ('subtitle_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subtitles.subtitlefile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subtitles.video')),
            ],
        ),
    ]
