# Generated by Django 3.1.4 on 2022-01-28 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subtitles', '0036_auto_20220120_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitleassignment',
            name='assigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subtitle_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
