# Generated by Django 3.1.4 on 2022-01-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0037_subtitleassignment_assigner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitleassignment',
            old_name='assigner',
            new_name='assigned_by',
        ),
    ]
