# Generated by Django 3.1.4 on 2022-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0038_auto_20220128_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['index'], 'permissions': (('start_translation', 'Can start translation'), ('start_transcription', 'Can start transcription'), ('start_standalone_translation', 'Can start standalone translation'), ('assign_user', 'Can assign user to subtitles'), ('cancel_workflow', 'Can cancel workflow'))},
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='status',
            field=models.CharField(choices=[('IT', 'Initial'), ('IN', 'In Progress'), ('AU', 'Auto Generated'), ('ED', 'Edited'), ('RE', 'Reviewed'), ('UP', 'Uploaded by user'), ('PU', 'Published'), ('QU', 'Queued'), ('WA', 'Waiting for review'), ('CH', 'Changes Requested'), ('AP', 'Approved')], default='IN', max_length=2),
        ),
    ]
